# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - uses: actions/checkout@v3
    - run: npm install ejs
    - name: Build blacklists
      run: node build.js
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x
        docker version
        docker build -t dns-zone-test test/
        docker run --rm -v ${{ env.GITHUB_WORKSPACE }}:/dns-zone-blacklist dns-zone-test
